name: Presale program

on:
  pull_request:
    branches:
      - main

env:
  SOLANA_CLI_VERSION: 2.1.0
  NODE_VERSION: 18.14.2
  ANCHOR_CLI_VERSION: 0.31.1

jobs:
  program_changed_files:
    runs-on: ubuntu-latest
    outputs:
      program: ${{steps.changed-files-specific.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v18.6
        with:
          files: |
            programs/presale

  program_tests:
    runs-on: ubuntu-latest
    needs: program_changed_files
    if: needs.program_changed_files.outputs.program == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-solana
      - uses: ./.github/actions/setup-dep
      - uses: ./.github/actions/setup-anchor
      # Cache rust, cargo
      - uses: Swatinem/rust-cache@v2
      - run: anchor build
        shell: bash
      - run: cargo test --package presale
        shell: bash
